[#137589183] Update renos-api-messages library versionnumber
nedap/retail-renos-api pull request #22
Opened 2017-01-13 11:18 UTC by rowanklg

2017-01-13 13:26 UTC, jaapdejong commented
Old files removed, but I do not see any new files added?

2017-01-16 11:06 UTC, flisijn requested changes
You did remove the 1.0 version in the local repo. But you did not add the 1.1 version to the local repo, such that the example code will not include any library at all...

2017-01-16 12:56 UTC, jaapdejong approved these changes

2017-01-16 13:26 UTC, flisijn approved these changes

2017-01-16 13:38 UTC, merged